version: '2'

services:
  redis:
    image: 'redis'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: rolodex
  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
volumes:
  redis:
