export const CLEAR_STATUS = 'CLEAR_STATUS';
export const UPDATE_STATUS = 'UPDATE_STATUS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_DONE = 'REGISTER_DONE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_DONE = 'UPDATE_PROFILE_DONE';

export const VERIFY_REGISTER_REQUEST = 'VERIFY_REGISTER_REQUEST';
export const VERIFY_REGISTER_SUCCESS = 'VERIFY_REGISTER_SUCCESS';
export const VERIFY_REGISTER_FAILURE = 'VERIFY_REGISTER_FAILURE';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_ERROR = 'CURRENT_USER_ERROR';

export const CLAIM_USER_DONE = 'CLAIM_USER_DONE';
export const CLAIM_USER_ERROR = 'CLAIM_USER_ERROR';

export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';
export const VERIFY_FORGOT_PASSWORD_CODE = 'VERIFY_FORGOT_PASSWORD_CODE';
export const RESET_PASSWORD_WITH_CODE = 'RESET_PASSWORD_WITH_CODE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
